AllCops:
  RunRailsCops: true
  Exclude:
    - Gemfile
    - lib/snippets/**/*
    - vendor/**/*
    - data/**/*
    - db/schema.rb
    - db/migrate/*
    - test/dummy/**/*
    - bin/rails
    - lib/shipit-engine.rb

inherit_from:
  .rubocop_todo.yml

Rails/FindEach:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - db/schema.rb

Style/DoubleNegation:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - lib/tasks/teams.rake
  Max: 120

Metrics/MethodLength:
  Max: 26

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 400

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/IndentHash:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/PredicateName:
  Exclude:
    - app/serializers/**/*

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/ExtraSpacing:
  AllowForAlignment: false

Style/GuardClause:
  Enabled: false
