language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
    - SUITE=rubocop
rvm:
  - 2.1
  - 2.2
matrix:
  fast_finish: true
  exclude:
    - env: SUITE=rubocop
      rvm: 2.2
notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
