addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
matrix:
  include:
    - rvm: 2.2.3
      env: SUITE=sqlite3
      gemfile: gemfiles/Gemfile-rails5

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
