addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3 # https://github.com/rails/rails/issues/24288#issuecomment-206011385
language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
    - SUITE=rubocop
rvm:
  - 2.2.3

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
