language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
rvm:
  - 2.2.3
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails5
matrix:
  fast_finish: true
  allow_failures:
    # Can't get db:schema:load to work with Rails 5 and sqlite3, allowing failures for now
    # https://github.com/Shopify/shipit-engine/pull/593#issuecomment-233947579
    - rvm: 2.2.3
      env: SUITE=sqlite3
      gemfile: gemfiles/Gemfile-rails5
  include:
    - rvm: 2.2.3
      env: SUITE=rubocop
      gemfile: Gemfile

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
