host: 'http://localhost:3000'
redis_url: 'redis://127.0.0.1:6379/0'

github_api:
  # Can be obtained there: https://github.com/settings/tokens/new
  # The required permissions are: `admin:org_hook`, `admin:repo_hook`, `read:org` and `repo`
  access_token:

# Can be obtained there: https://github.com/settings/applications/new
# Set the "Authorization callback URL" as `<host>/github/auth/github/callback`
github_oauth: 
  id:
  secret:
  # teams: # Optional

# To work on the beta bootstrap re-write
# features:
#   - bootstrap

